version: '3.6'

services:

  mongo_identity:
    image: mongo:5.0
    container_name: mongo_identity
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  identity:
    container_name: identity
    build:
      context: .
      target: dev
    ports:
      - 8080:8080
    volumes:
      - ./identity/:/code/identity
    depends_on:
      - mongo_identity